config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'choose_team/index'

  resources :teams do
  	resources :players
  	resources :games
  end

  root "home#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
	after_create :set_default_association

	validates :rival, :presence => true

	belongs_to :team
	belongs_to :category

	has_many :game_statistics

	def set_default_association
		# players game_statistic db create automatically
	end
end

app/models/game_statistic.rb
class GameStatistic < ActiveRecord::Base
	belongs_to :game
end

app/models/player.rb
class Player < ActiveRecord::Base
	after_create :set_default_association

	validates :number, :name, :presence => true	
	validates :number, :inclusion => { :in => 0..99, :message => "請選擇號碼0至99號" }
	validates :number, :uniqueness => { scope: :team, message: "同一隊中不能有一樣的號碼" }
	
	belongs_to :team
	has_one :statistic, dependent: :destroy
	has_many :game_statistic, dependent: :destroy

	private 

	def set_default_association
	  self.create_statistic
	end
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
	belongs_to :player
end

app/models/team.rb
class Team < ActiveRecord::Base
	validates :name, :presence => true

	has_many :players
	has_many :games
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?


   protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
   	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
   end
end

app/controllers/choose_team_controller.rb
class ChooseTeamController < ApplicationController
  def index
  	@teams = Team.all
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :find_team
	before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

	def index
		@games = @team.games
	end

	def show
		@game = @team.games.find(params[:id])
		@players = @team.players
	end

	def new
		@game = @team.games.new
	end

	def create
		@game = @team.games.new game_params

		if @game.save
			redirect_to team_games_path(@team), notice: '賽事新增成功！'
		else
			render :new
		end
	end

	def edit
		@game = @team.games.find(params[:id])
	end

	def update
		@game = @team.games.find(params[:id])

		if @game.update game_params
			redirect_to team_games_path(@team), notice: '賽事修改成功！'
		else
			render :edit
		end
	end

	def destroy
		@game = @team.games.find(params[:id])
		if @game.destroy
			redirect_to team_games_path(@team), alert: '已刪除該賽事！'
		end
	end

	private

	def game_params
		params.require(:game).permit(:category_id, :rival)
	end

	def find_team
		@team = Team.find(params[:team_id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :find_team
	before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

	def new
		@player = @team.players.new
	end
	
	def create
		@player = @team.players.new(player_params)

		if @player.save
			redirect_to team_path(@team), notice: '隊員新增成功！'
		else
			render :new
		end
	end

	def edit
		@player = @team.players.find(params[:id])
	end

	def update
		@player = @team.players.find(params[:id])

		if @player.update player_params
			redirect_to team_path(@team), notice: '隊員修改成功！'
		else
			render :edit
		end
	end

	def destroy
		@player = @team.players.find(params[:id])
		if @player.destroy
			redirect_to team_path(@team), alert: '已刪除隊員！'
		end
	end

	def show
		# for player analysis
		@player = @team.players.find(params[:id])
		@statistic = @player.statistic
	end

	private

	def player_params
		params.require(:player).permit(:number, :name)
	end

	def find_team
		@team = Team.find(params[:team_id])
	end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController	
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @players = @team.players
    @games = @team.games
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: '已成功建立隊伍' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: '修改完畢！' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, alert: '隊伍已刪除' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice_message
    alert_types = { :notice => :success, :alert => :danger }

    close_button_options = { :class => "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, :class => alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/choose_team_helper.rb
module ChooseTeamHelper
end

app/helpers/games_helper.rb
module GamesHelper
	def category_options
        Category.all.map{ |c| [c.name, c.id] }
    end

    def category_and_date game
    	"#{Category.find(game.category_id).name}@#{game.created_at.strftime("%B %d, %Y")}"
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/choose_team/index.html.erb
<div class="col-md-12 text-center">
	<h1> 選擇球隊 </h1>
	<hr>

	<% @teams.each do |team| %>
		<h3> <%= link_to(team.name, team_games_path(team))  %> </h3>
		<br>
	<% end %>
</div>

app/views/games/_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= form_for [@team,@game] do |f| %>
      <% if @game.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@game.errors.count, "errors") %> prohibited this game from being saved:</h2>

          <ul>
          <% @game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
    <div class="form-inputs">
      <br>
        <%= f.select(:category_id, category_options, {}, :class => "form-control", :prompt => "賽事種類") %>
      <br>
      <%= f.text_field :rival, :class => "form-control", :placeholder => "對手名稱" %>
    </div>
    
    <hr>
    <div class="form-actions">
      <%= f.submit "確定", :class => "btn btn-primary"%>
    </div>
  <% end %> 
</div>

app/views/games/edit.html.erb
<h1 class="text-center"> 修改賽事 </h1>

<%= render 'form' %>

app/views/games/index.html.erb
<div class="col-md-12"> 
  
<h1 class="text-center"> 賽事記錄 </h1>

  <div class="group">
    <%= link_to("新增賽事", new_team_game_path, :class => "btn btn-primary pull-right" ) %>
  </div>
  <%= render :partial => "teams/games_table" %>    

</div>

app/views/games/new.html.erb
<h1 class="text-center"> 新增賽事 </h1>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="col-md-12"> 
	  
	<h1 class="text-center"> <%= category_and_date @game %> - 逐場數據 </h1>

	<table class="table">
    <thead>
      <tr>
        <th> 背號 </th>
        <th> 姓名 </th>
        <th> 兩分 </th>
        <th> 三分 </th>
        <th> 攻-守 <br> 籃 板 </th>
        <th> 助攻 </th>
        <th> 阻攻 </th>
        <th> 抄截 </th>
        <th> 失誤 </th>
        <th> 犯規 </th>
        <th> 罰球 </th>
        <th> 得分 </th>
        <th>  </th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %> 
        <tr>
          <td> #<%= player.number %> </td>
          <td> <%= link_to player.name, team_player_path(player.team, player) %>
          <td> <%=  %> </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td>  </td>
          <td> 
            <%= link_to("更新數據", '#', :class => "btn btn-warning" ) %>
          </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class="row">     
  <div class="col-lg-12 text-center v-center">
  <h1>籃球盒子</h1>
  
  <p class="lead"> 記錄走過得每一刻，規劃球隊的未來 </p>
        
  <br>
          
  <form class="col-lg-12">
    <div class="input-group input-group-lg col-sm-offset-4 col-sm-4">
      <input type="text" class="center-block form-control input-lg" title="Enter you email." placeholder="輸入電子郵件">
      <span class="input-group-btn">
          <button class="btn btn-lg btn-primary" type="button">OK</button>
      </span>
    </div>
  </form>
</div>

app/views/players/_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= form_for [@team,@player] do |f| %>
      <% if @player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@player.errors.count, "errors") %> prohibited this player from being saved:</h2>

          <ul>
          <% @player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
    <div class="form-inputs">
      <br>
      <%= f.number_field :number, :class => "form-control", :placeholder => "背號" %>
      <br>
      <%= f.text_field :name, :class => "form-control", :placeholder => "姓名" %>
    </div>
    
    <hr>
    <div class="form-actions">
      <%= f.submit "確定", :class => "btn btn-primary"%>
    </div>
  <% end %> 
</div>

app/views/players/edit.html.erb
<h1 class="text-center"> 修改隊員資料 </h1>

<%= render 'form' %>

app/views/players/new.html.erb
<h1 class="text-center"> 新增隊員 </h1>

<%= render 'form' %>

app/views/players/show.html.erb
<div class="col-md-12"> 
  
<h1 class="text-center"> <%= @player.name %> - 歷史數據 </h1>

<table class="table">
    <thead>
      <tr>
        <th> 背號 </th>
        <th> 兩分 </th>
        <th> 三分 </th>
        <th> 攻-守 <br> 籃 板 </th>
        <th> 助攻 </th>
        <th> 阻攻 </th>
        <th> 抄截 </th>
        <th> 失誤 </th>
        <th> 犯規 </th>
        <th> 罰球 </th>
        <th> 得分 </th>
        <th>  </th>
      </tr>
    </thead>
    <tbody>
    	<tr>
      	<td> #<%= @player.number %> </td>
      	<td> <%= @player.statistic.two_pt %> </td>
        <td> <%= @player.statistic.three_pt %> </td>
        <td> 
        	<%= @player.statistic.off_rebound %> -
        	<%= @player.statistic.def_rebound %>
        </td>
        <td> <%= @player.statistic.assist %> </td>
        <td> <%= @player.statistic.block %> </td>
        <td> <%= @player.statistic.steal %> </td>
        <td> <%= @player.statistic.turnover %> </td>
        <td> <%= @player.statistic.foul %> </td>
        <td> <%= @player.statistic.free_throw %> </td>
        <td> <%= @player.statistic.points %> </td>
        <td> 
          <%= link_to("更新數據", '#', :class => "btn btn-warning" ) %>
        </td>   
    	</tr>

    </tbody>
  </table>

</div>